services:
  mysql-bio-db:
    image: mysql
    container_name: bio-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bio_db
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql-bio-db
    environment:
      PMA_HOST: mysql-bio-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
  backend:
    build: .
    container_name: back
    links:
      - mysql-bio-db
    environment: 
      MYSQL_HOST: mysql-bio-db
    depends_on:
      - mysql-bio-db 
    volumes:
      - ./maps:/home/app/maps
  front:
    build: ./frontend
    environment: 
      API_HOST: backend
      API_PORT: 8080
    links:
      - backend
    ports:
      - 80:80
