services:
  mysql-bio-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bio_db
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql-bio-db
    environment:
      PMA_HOST: mysql-bio-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  nginx:
    image: nginx
    #    depends_on:
    ports:
      - 80:80
    volumes:
      - ./static_data:/var/www/bio-app/static
      - ./nginx-config.d:/etc/nginx/conf.d
