services:
  mysql-bio-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql-psw"
      MYSQL_DATABASE: "bio_db"
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
